"""
cocotools/pass1.py — First assembly pass
Faithful Python translation of lwasm/pass1.c
(William Astle, LWTools, GPL v3)
Source: http://lwtools.projects.l-w.ca/

Pass 1:
  - Reads every source line via InputSystem.readline()
  - Creates a Line object for each source line
  - Assigns assembly addresses as expression trees
    (addr = prev.addr + LINELEN(prev), lazily reduced)
  - Parses the opcode and operand via instab callbacks
  - Registers labels in the symbol table
  - Handles internal directives (\\x01\\x01...) generated by macros

C → Python mapping:
  goto linedone      → `line_done = True` flag; fall through to symbol reg
  goto nextline      → `continue` in the main loop
  char **p  / p1     → simple integer index `pi` into the line string
  lw_free(sym)       → no-op (GC)
  expand_macro(...)  → as_.expand_macro(cl, sym) [deferred to macro.py]
  expand_struct(...) → as_.expand_struct(cl, sym) [deferred to struct.py]
  add_macro_line(...)→ as_.add_macro_line(line)   [deferred to macro.py]

Line format (PRAGMA_NEWSOURCE *not* in effect):
  [<symbol>] <opcode> <operand>[ <comment>]

  Symbol at column 0 *or* followed by ':' or '='
  Optional numeric line number at start (BASIC style)
  Comment characters: * ; #
  No spaces in operand (except under PRAGMA_NEWSOURCE)
"""

from .lwasm_types import (
    OUTPUT_OS9,
    PRAGMA_6809, PRAGMA_6309CONV, PRAGMA_6809CONV, PRAGMA_NEWSOURCE,
    PRAGMA_FORWARDREFMAX, PRAGMA_EMUEXT, PRAGMA_6800COMPAT,
    PRAGMA_TESTMODE, PRAGMA_SHADOW,
    E_OPCODE_BAD, E_6309_INVALID, E_6809_INVALID, E_OPERAND_BAD,
    symbol_flag_none,
    lwasm_expr_linelen, lwasm_expr_linedlen,
)
from .lw_expr import Expr, OPER_PLUS, TYPE_SPECIAL
from .lwasm_core import AsmState, Line, curpragma
from .input_system import InputSystem


# ─────────────────────────────────────────────────────────────────────────────
# Instab flag constants  (enum in instab.h)
# ─────────────────────────────────────────────────────────────────────────────

lwasm_insn_cond      = 1        # conditional instruction
lwasm_insn_endm      = 1 << 1   # end of macro
lwasm_insn_setsym    = 1 << 2   # insn sets symbol address
lwasm_insn_is6309    = 1 << 3   # 6309-only instruction
lwasm_insn_struct    = 1 << 4   # allowed inside STRUCT
lwasm_insn_setdata   = 1 << 5   # use daddr (not addr) for symbol
lwasm_insn_is6800    = 1 << 6   # 6800 compatibility opcode
lwasm_insn_is6809    = 1 << 7   # 6809-only instruction
lwasm_insn_is6809conv= 1 << 8   # 6809 convenience opcode
lwasm_insn_is6309conv= 1 << 9   # 6309 convenience opcode
lwasm_insn_isemuext  = 1 << 10  # emulator extension
lwasm_insn_org       = 1 << 11  # sets assembly address
lwasm_insn_normal    = 0


# ─────────────────────────────────────────────────────────────────────────────
# InstaEntry — wraps one INSTAB entry for pass1 use
# ─────────────────────────────────────────────────────────────────────────────

class InstaEntry:
    """
    Mirrors instab_t { char *opcode; int ops[4]; parse; resolve; emit; flags }
    Built on the fly from the INSTAB dict in instab.py.
    """
    __slots__ = ('opcode', 'flags', 'parse', 'resolve', 'emit')

    def __init__(self, opcode, flags=lwasm_insn_normal,
                 parse=None, resolve=None, emit=None):
        self.opcode  = opcode
        self.flags   = flags
        self.parse   = parse    # callable(as_, cl, p_ref) or None
        self.resolve = resolve  # callable(as_, cl, force) or None
        self.emit    = emit     # callable(as_, cl) or None


def _instab_lookup(as_, cl, sym):
    """
    Search the instruction table for `sym` (case-insensitive).
    Returns (opnum, InstaEntry) if found, else (-1, None).
    Mirrors the for-loop in pass1.c including pragma filters.
    """
    from .instab import INSTAB_BY_NAME   # O(1) dict lookup

    upper = sym.upper()
    ie = INSTAB_BY_NAME.get(upper)
    if ie is None:
        return -1, None

    flags = ie.flags

    # Apply pragma-based filters (matches the for-loop body in pass1.c)
    if (flags & lwasm_insn_is6800)     and not curpragma(cl, PRAGMA_6800COMPAT):
        return -1, None
    if (flags & lwasm_insn_is6809conv) and not curpragma(cl, PRAGMA_6809CONV):
        return -1, None
    if (flags & lwasm_insn_is6809conv) and not curpragma(cl, PRAGMA_6809):
        return -1, None
    if (flags & lwasm_insn_is6309conv) and not curpragma(cl, PRAGMA_6309CONV):
        return -1, None
    if (flags & lwasm_insn_isemuext)   and not curpragma(cl, PRAGMA_EMUEXT):
        return -1, None

    return ie.opnum, ie


# ─────────────────────────────────────────────────────────────────────────────
# do_pass1(as_)  — faithful translation of do_pass1() in pass1.c
# ─────────────────────────────────────────────────────────────────────────────

def do_pass1(as_):
    """
    do_pass1(asmstate_t *as):
    Read every source line, build the line list, assign addresses, and
    register symbols.

    The C function uses goto; Python restructures as:
      goto linedone  → set line_done=True, fall through to symbol reg
      goto nextline  → `continue` at end of loop iteration
    """

    # Ensure the input system is attached
    if not hasattr(as_, 'input') or as_.input is None:
        as_.input = InputSystem(as_)

    lc = 1         # current line-counter override (0 = don't override)

    while True:
        sym      = None
        nomacro  = False
        line_done = False       # replaces "goto linedone"

        # ── read next source line ─────────────────────────────────────────────
        line = as_.input.readline()
        if line is None:
            break

        # ── internal directives  (\x01\x01...) ───────────────────────────────
        # These are injected by the macro/include system and do NOT produce
        # Line objects.
        if len(line) >= 2 and line[0] == '\x01' and line[1] == '\x01':
            # find end of directive keyword
            i = 2
            while i < len(line) and not line[i].isspace():
                i += 1
            directive = line[2:i]
            arg       = line[i+1:] if i < len(line) else ''

            if directive == 'SETCONTEXT':
                as_.context = int(arg.strip()) if arg.strip() else 0
            elif directive == 'SETLINENO':
                lc = int(arg.strip()) if arg.strip() else 0
            elif directive == 'SETNOEXPANDSTART':
                if as_.line_tail:
                    as_.line_tail.noexpand_start += 1
            elif directive == 'SETNOEXPANDEND':
                if as_.line_tail:
                    as_.line_tail.noexpand_end += 1

            if lc == 0:
                lc = 1
            continue

        # ── snapshot macro state before creating the line ────────────────────
        wasmacro = as_.inmacro

        # ── create Line object ────────────────────────────────────────────────
        cl = Line(as_)
        cl.outputl  = -1
        cl.linespec  = as_.input.curspec() or ''
        cl.prev      = as_.line_tail
        cl.insn      = -1
        cl.inmod     = as_.inmod
        cl.csect     = as_.csect
        cl.pragmas   = as_.pragmas
        cl.context   = as_.context
        cl.ltext     = line
        cl.soff      = -1
        cl.dshow     = -1
        cl.dsize     = 0
        cl.dptr      = None
        cl.isbrpt    = 0
        cl.dlen      = 0
        as_.cl = cl

        if not as_.line_tail:
            # First line: address 0
            as_.line_head = cl
            cl.addr  = Expr.int(0)
            cl.daddr = Expr.int(0)
        else:
            # as->line_tail->next = cl  (forward link — C sets this here)
            cl.prev.next = cl
            # addr = prev.addr + LINELEN(prev)
            te      = Expr.special(lwasm_expr_linelen, cl.prev)
            cl.addr = Expr.oper(OPER_PLUS, cl.prev.addr, te)
            as_.reduce_expr(cl.addr)

            # Phase propagation from previous line
            if cl.prev.phase:
                te        = Expr.special(lwasm_expr_linelen, cl.prev)
                cl.phase  = Expr.oper(OPER_PLUS, cl.prev.phase, te)
                as_.reduce_expr(cl.phase)

            # OS-9 data address
            if as_.output_format == OUTPUT_OS9:
                te       = Expr.special(lwasm_expr_linedlen, cl.prev)
                cl.daddr = Expr.oper(OPER_PLUS, cl.prev.daddr, te)
                as_.reduce_expr(cl.daddr)
            else:
                cl.daddr = Expr.copy(cl.addr)

            # Carry DP value forward
            cl.dpval = cl.prev.dpval

        # ── line number assignment ─────────────────────────────────────────────
        # If lc is set, use it as the lineno; otherwise increment from prev.
        if as_.line_tail:
            if not lc and cl.linespec != cl.prev.linespec:
                lc = 1
            if lc:
                cl.lineno = lc
                lc = 0
            else:
                cl.lineno = (as_.line_tail.lineno + 1) if as_.line_tail else 1
        else:
            cl.lineno = lc if lc else 1
            lc = 0

        as_.line_tail = cl

        # ── blank / pure-comment lines ─────────────────────────────────────────
        # Blank lines cause a local-symbol context break.
        # Comment-only lines do NOT.
        if not line:
            as_.context = as_.next_context()
            _finish_line(as_, cl, line, wasmacro)
            continue

        if line[0] in ('*', ';', '#'):
            # Comment — no context break; skip to nextline
            _finish_line(as_, cl, line, wasmacro)
            continue

        # ── skip optional line number (BASIC-style, non-NEWSOURCE) ────────────
        pi = 0      # parse index into `line`
        if line[pi].isdigit() and not curpragma(cl, PRAGMA_NEWSOURCE):
            j = pi
            while j < len(line) and line[j].isdigit():
                j += 1
            if j < len(line) and line[j].isspace():
                pi = j + 1
            # else: not a valid line number prefix, stay at pi=0

        # ── blank / comment after line number ─────────────────────────────────
        if pi >= len(line) or not line[pi:].strip():
            as_.context = as_.next_context()
            _finish_line(as_, cl, line, wasmacro)
            continue

        if line[pi] in ('*', ';', '#'):
            _finish_line(as_, cl, line, wasmacro)
            continue

        # ── skip leading whitespace; remember if we started in col 0 ──────────
        stspace = line[pi].isspace()
        if stspace:
            while pi < len(line) and line[pi].isspace():
                pi += 1

        if pi >= len(line):
            as_.context = as_.next_context()
            _finish_line(as_, cl, line, wasmacro)
            continue

        # ── find the end of the first token ───────────────────────────────────
        # Scan to whitespace, ':', or '='
        tok_start = pi
        while pi < len(line) and not line[pi].isspace() \
              and line[pi] != ':' and line[pi] != '=':
            pi += 1
        tok_end = pi

        # ── decide if tok is a symbol ─────────────────────────────────────────
        # A token is a symbol if:
        #   - it's followed immediately by ':' or '='  (explicit label marker)
        #   - OR it started at column 0 (stspace==False), meaning no leading WS
        if tok_end < len(line) and line[tok_end] in (':', '=') or not stspace:
            tok = line[tok_start:tok_end]
            if tok and tok[0] in ('*', ';', '#'):
                # it was a comment marker treated as a symbol — go to linedone
                line_done = True
            else:
                sym = tok
                if tok_end < len(line) and line[tok_end] == ':':
                    pi = tok_end + 1
                else:
                    pi = tok_end

                # skip whitespace after symbol
                while pi < len(line) and line[pi].isspace():
                    pi += 1

                if pi < len(line) and line[pi] == '=':
                    tok_start = pi
                    pi += 1
                    tok_end = pi
                else:
                    tok_start = pi
                    while pi < len(line) and not line[pi].isspace():
                        pi += 1
                    tok_end = pi

        # ── branch-point symbol (!) ────────────────────────────────────────────
        if sym == '!':
            cl.isbrpt = 1
            sym = None
        elif sym:
            cl.sym = sym
        cl.symset = 0

        # ── tok now points to the opcode token ────────────────────────────────
        # tok_start:tok_end is the opcode string within `line`
        opcode_str = line[tok_start:tok_end].strip()

        if not line_done and opcode_str:
            # ── inhibit macro expansion prefix (??) ───────────────────────────
            if opcode_str.startswith('??'):
                nomacro    = True
                opcode_str = opcode_str[2:]
                tok_start += 2

            # Advance pi past opcode, skip whitespace to operand
            pi = tok_end
            while pi < len(line) and line[pi].isspace():
                pi += 1
            # p1 (operand start) = pi

            # ── testmode: strip test comment from line copy ────────────────────
            if curpragma(cl, PRAGMA_TESTMODE):
                tidx = line.find(';.', pi)
                if tidx >= 0:
                    line = line[:tidx]

            # ── opcode lookup ──────────────────────────────────────────────────
            opnum, ie = _instab_lookup(as_, cl, opcode_str)

            # If the opcode token is itself a comment character: linedone
            if ie is None and opcode_str and opcode_str[0] in ('*', ';', '#'):
                line_done = True

            if not line_done:
                # ── still inside macro definition → collect line ───────────────
                if as_.inmacro and not (ie and (ie.flags & lwasm_insn_endm)):
                    line_done = True

                elif as_.skipcond and not (ie and (ie.flags & lwasm_insn_cond)):
                    # skipping a conditional block
                    line_done = True

                else:
                    # ── macro shadow check (PRAGMA_SHADOW) ────────────────────
                    if not nomacro and (as_.pragmas & PRAGMA_SHADOW):
                        if hasattr(as_, 'expand_macro') and \
                                as_.expand_macro(cl, opcode_str, line[pi:]) == 0:
                            line_done = True

                    if not line_done:
                        if ie is None or \
                           (curpragma(cl, PRAGMA_6809) and ie.flags & lwasm_insn_is6309) or \
                           (not curpragma(cl, PRAGMA_6809) and ie.flags & lwasm_insn_is6809):
                            # Unknown opcode — try macro / struct expansion
                            cl.insn = -1
                            if opcode_str and opcode_str[0] not in (';', '*'):
                                expanded = False
                                if not nomacro and hasattr(as_, 'expand_macro'):
                                    if as_.expand_macro(cl, opcode_str, line[pi:]) == 0:
                                        expanded = True
                                if not expanded and hasattr(as_, 'expand_struct'):
                                    if as_.expand_struct(cl, opcode_str, line[pi:]) == 0:
                                        expanded = True
                                if not expanded:
                                    if curpragma(cl, PRAGMA_6809) and ie and \
                                            ie.flags & lwasm_insn_is6309:
                                        as_.register_error2(cl, E_6309_INVALID,
                                                            '(%s)', opcode_str)
                                    elif not curpragma(cl, PRAGMA_6809) and ie and \
                                            ie.flags & lwasm_insn_is6809:
                                        as_.register_error2(cl, E_6809_INVALID,
                                                            '(%s)', opcode_str)
                                    else:
                                        as_.register_error(cl, E_OPCODE_BAD)
                        else:
                            # Valid opcode found
                            cl.insn = opnum
                            if ie.parse:
                                if curpragma(cl, PRAGMA_6809) and \
                                        ie.flags & lwasm_insn_is6309:
                                    as_.register_error2(cl, E_6309_INVALID,
                                                        '(%s)', opcode_str)
                                if not curpragma(cl, PRAGMA_6809) and \
                                        ie.flags & lwasm_insn_is6809:
                                    as_.register_error2(cl, E_6809_INVALID,
                                                        '(%s)', opcode_str)

                                if as_.instruct == 0 or \
                                        ie.flags & lwasm_insn_struct:
                                    cl.len = -1
                                    # Call parse function with operand string
                                    operand = line[pi:]
                                    remaining = ie.parse(as_, cl, operand)
                                    # remaining is the unconsumed operand tail

                                    # PRAGMA_FORWARDREFMAX: force resolution
                                    if curpragma(cl, PRAGMA_FORWARDREFMAX) and \
                                            ie.resolve:
                                        ie.resolve(as_, cl, 1)

                                    # Synchronise len and dlen
                                    if cl.inmod == 0 and \
                                            cl.len >= 0 and cl.dlen >= 0:
                                        if cl.len == 0:
                                            cl.len  = cl.dlen
                                        else:
                                            cl.dlen = cl.len

                                    # Check for unconsumed operand
                                    leftover = remaining.strip() \
                                        if isinstance(remaining, str) else ''
                                    if not curpragma(cl, PRAGMA_NEWSOURCE):
                                        if leftover and not cl.err:
                                            as_.register_error2(
                                                cl, E_OPERAND_BAD,
                                                '(%s)', leftover)
                                    else:
                                        leftover = leftover.lstrip()
                                        if leftover and leftover[0] not in \
                                                (';', '#'):
                                            as_.register_error2(
                                                cl, E_OPERAND_BAD,
                                                '%s', leftover)

                                    # Early expression reduction
                                    as_.reduce_line_exprs(cl)

                                elif as_.instruct == 1:
                                    as_.register_error2(cl, E_OPERAND_BAD,
                                                        '(%s)', line[pi:])

        # ── linedone: ─────────────────────────────────────────────────────────
        # In the C code 'linedone' is the label just before symbol registration.
        # Macro collection happens here first.
        if as_.inmacro and wasmacro:
            if hasattr(as_, 'add_macro_line'):
                as_.add_macro_line(line)

        # Symbol registration (skipped during skipcond or inside macro)
        if not as_.skipcond and not as_.inmacro:
            if cl.sym and not cl.symset:
                ie2 = None
                if cl.insn >= 0:
                    from .instab import INSTAB
                    if cl.insn < len(INSTAB):
                        ie2 = INSTAB[cl.insn]

                use_daddr = (ie2 is not None and
                             ie2.flags & lwasm_insn_setdata)
                val = cl.daddr if use_daddr else \
                      (cl.phase if cl.phase else cl.addr)
                as_.register_symbol(cl, cl.sym, val, symbol_flag_none)

        # ── nextline: ─────────────────────────────────────────────────────────
        _finish_line(as_, cl, line, wasmacro)

        if as_.endseen:
            return


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _finish_line(as_, cl, line, wasmacro):
    """
    Code that runs at 'nextline:' in C:
      - Hide lines inside conditionals or macros
      - Preprocess output
      - Check for END
    """
    if as_.skipcond or as_.inmacro or \
            (line and line[0] == '\x01'):
        cl.hideline = 1
    if as_.skipcond:
        cl.hidecond = 1

    # Preprocess output (-P flag)
    if as_.preprocess and not cl.hideline:
        print(cl.ltext)
